version: "2"
services:
  dagda:
    build: .
    image: 3grander/dagda:0.8.0
    container_name: dagda
    networks:
      - mdb
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp:/tmp
    depends_on:
      - vulndb
  vulndb:
    image: mongo
    container_name: vulndb
    networks:
      - mdb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
networks:
  mdb:
    external: false
